branches:
  only:
    - master
    - develop

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-ng && npm run ci.tslint
    - stage: "Build and WebPack"
      os: osx
      env:
        - WebPackiOS="11"
      osx_image: xcode9.3
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && npm i && tns build ios --env.uglify --env.snapshot && cd ../demo-ng && npm i && tns build ios --env.uglify --env.snapshot --env.aot
    - language: android
      os: linux
      env:
        - WebPackAndroid="26"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: cd demo && npm run build.plugin && npm i && tns build android --env.uglify --env.snapshot && cd ../demo-ng && npm i && tns build android --env.uglify --env.snapshot --env.aot
    - env:
        - BuildAndroid="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android && cd ../demo-ng && tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.3"
      osx_image: xcode9.3
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios && cd ../demo-ng && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-23
    - android-26
    - extra-android-m2repository

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
