branches:
  only:
    - master

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-ng && npm run ci.tslint
    - stage: "Build and WebPack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode10.0
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify --env.snapshot && cd ../demo-ng && npm i && tns build ios --bundle --env.uglify --env.snapshot --env.aot
    - language: android
      os: linux
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script: cd demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot && cd ../demo-ng && npm i && tns build android --bundle --env.uglify --env.snapshot --env.aot
    - env:
        - BuildAndroid="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android && cd ../demo-ng && tns build android
    - os: osx
      env:
        - BuildiOS="12.0"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios && cd ../demo-ng && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
